/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ed.escalante
 */
public class WhiteBalancePanel extends javax.swing.JPanel {
    private Hush hush;
    /**
     * Creates new form WhiteBalancePanel
     */
    public WhiteBalancePanel() {
        initComponents();
        this.hush = Hush.hush;
        System.out.println("Hi there Titan");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        label5 = new java.awt.Label();
        label7 = new java.awt.Label();
        label2 = new java.awt.Label();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        label8 = new java.awt.Label();

        setMaximumSize(new java.awt.Dimension(404, 54));
        setPreferredSize(new java.awt.Dimension(404, 54));
        setSize(new java.awt.Dimension(404, 54));
        setLayout(new java.awt.GridLayout(2, 4));

        label1.setText("label1");
        add(label1);

        label3.setText("label3");
        add(label3);

        label5.setText("label5");
        add(label5);

        label7.setText("label7");
        add(label7);

        label2.setText("label2");
        add(label2);

        label4.setText("label4");
        add(label4);

        label6.setText("label6");
        add(label6);

        label8.setText("label8");
        add(label8);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    // End of variables declaration//GEN-END:variables
}
